services:
  postgres:
    image: postgres:16.1
    container_name: postgres_graphql
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready -U postgres
      interval: 3s
      timeout: 2s
      retries: 3
    ports:
      - 5432:5432
    volumes:
      - db-pgdb:/var/lib/postgresql/data
      - ./docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
volumes:
  db-pgdb:
